apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: jhnginx
        image: 211.183.3.115/project/project:jh  # Docker 이미지 주소
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: harbor-registry
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: NodePort  # NodePort 타입 추가 (외부에서 접근 가능하게 설정)
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080  # 원하는 NodePort 번호 설정 가능
